### ISSUE TITLE
Database should not be queried until system is enabled

### ISSUE THREAD

**Issue by davidalexander** [sonassi/magestack-queue#1]
# Current

After the code of the module is been installed (and added to the application's bootstrap file), but before the database has been installed (via `php queue.php --install`), the application is in a broken state.

Even though the default `config.php` file has `'enabled' => false`, the database (which has not yet been created) is queried and this results in warnings and errors on the site:

    Warning: SQLite3::query(): Unable to prepare statement: 1, no such table: queue in /vendor/magestack/queue/src/Backend/SQLite.php on line 18

    Fatal error: Uncaught Error: Call to a member function fetchArray() on boolean in /vendor/magestack/queue/src/Queue.php on line 18

    Error: Call to a member function fetchArray() on boolean in /vendor/magestack/queue/src/Queue.php on line 181

# Expected

The code can be installed in a disabled state without breaking the frontend by not querying the database until `'enabled' => true`. This would ease deployment in that the code implementation could be deployed first, then the database installed and configured and finally, the system enabled.

**Comment by clockworkgeek** [comment]
Now the database cannot be installed until the module is enabled, and the module starts off disabled. Maybe the `--install` and `--status` options should be exempt from disabled status?
